apiVersion: v1
kind: ConfigMap
metadata:
  name: cleocog-config
data:
  DB_SERVICE_URL: "http://db-service.default.svc.cluster.local"
  LLM_PROMPT_SERVICE_URL: "http://llm-prompt-service.default.svc.cluster.local"
  EXTRACTOR_SERVICE_URL: "http://extractor-service.default.svc.cluster.local"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleocog-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cleocog-backend
  template:
    metadata:
      labels:
        app: cleocog-backend
    spec:
      containers:
        - name: cleocog-container
          image: manavkhandurie/cleocog:backendservice_v1_0_0
          ports:
            - containerPort: 8000
          env:
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: cleocog-secret
                  key: S3_BUCKET_NAME
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: cleocog-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cleocog-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: cleocog-secret
                  key: AWS_DEFAULT_REGION
            - name: DB_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: cleocog-config
                  key: DB_SERVICE_URL
            - name: LLM_PROMPT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: cleocog-config
                  key: LLM_PROMPT_SERVICE_URL
            - name: EXTRACTOR_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: cleocog-config
                  key: EXTRACTOR_SERVICE_URL

---
apiVersion: v1
kind: Service
metadata:
  name: cleocog-backend-service
spec:
  type: NodePort
  selector:
    app: cleocog-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080  # optional, or remove to let K8s assign
