[tool.poetry]
name = "embeddingservice"
version = "0.1.0"
description = "EMBDEDDING MICROSERVICE FOR CLEOCOG"
readme = "README.md"
requires-python = ">=3.11,<4.0"
packages = [{ include = "app" }]


[tool.poetry.dependencies]
python = "^3.8"  
annotated-types = "==0.7.0"
anyio = "==4.9.0"
certifi = "==2025.4.26"
charset-normalizer = "==3.4.2"
click = "==8.1.8"
colorama = "==0.4.6"
fastapi = "==0.115.12"
filelock = "==3.18.0"
fsspec = "==2025.3.2"
h11 = "==0.16.0"
huggingface-hub = "==0.30.2"
idna = "==3.10"
jinja2 = "==3.1.6"
joblib = "==1.5.0"
markupsafe = "==3.0.2"
mpmath = "==1.3.0"
networkx = "==3.4.2"
numpy = "==2.2.5"
packaging = "==25.0"
pillow = "==11.2.1"
pydantic = "==2.11.4"
pydantic-core = "==2.33.2"
pyyaml = "==6.0.2"
regex = "==2024.11.6"
requests = "==2.32.3"
safetensors = "==0.5.3"
scikit-learn = "==1.6.1"
scipy = "==1.15.2"
sentence-transformers = "==4.1.0"
sniffio = "==1.3.1"
starlette = "==0.46.2"
sympy = "==1.14.0"
threadpoolctl = "==3.6.0"
tokenizers = "==0.21.1"
torch = "==2.7.0"
tqdm = "==4.67.1"
transformers = "==4.51.3"
typing-inspection = "==0.4.0"
typing-extensions = "==4.13.2"
urllib3 = "==2.4.0"
uvicorn = "==0.34.2"
backports-tarfile = "==1.2.0"
build = "==1.2.2.post1"
cachecontrol = "==0.14.3"
cleo = "==2.1.0"
crashtest = "==0.4.1"
distlib = "==0.3.9"
dnspython = "==2.7.0"
dulwich = "==0.22.8"
email-validator = "==2.2.0"
fastapi-cli = "==0.0.7"
fastjsonschema = "==2.21.1"
findpython = "==0.6.3"
httpcore = "==1.0.9"
httptools = "==0.6.4"
httpx = "==0.28.1"
importlib-metadata = "==8.7.0"
installer = "==0.7.0"
itsdangerous = "==2.2.0"
jaraco-classes = "==3.4.0"
jaraco-context = "==6.0.1"
jaraco-functools = "==4.1.0"
keyring = "==25.6.0"
markdown-it-py = "==3.0.0"
mdurl = "==0.1.2"
more-itertools = "==10.7.0"
msgpack = "==1.1.0"
orjson = "==3.10.18"
pbs-installer = "==2025.4.9"
pkginfo = "==1.12.1.2"
platformdirs = "==4.3.8"
poetry = "==2.1.3"
poetry-core = "==2.1.3"
pydantic-extra-types = "==2.10.4"
pydantic-settings = "==2.9.1"
pygments = "==2.19.1"
pyproject-hooks = "==1.2.0"
python-dotenv = "==1.1.0"
python-multipart = "==0.0.20"
pywin32-ctypes = "==0.2.3"
rapidfuzz = "==3.13.0"
requests-toolbelt = "==1.0.0"
rich = "==14.0.0"
rich-toolkit = "==0.14.6"
shellingham = "==1.5.4"
tomlkit = "==0.13.2"
trove-classifiers = "==2025.5.9.12"
typer = "==0.15.3"
ujson = "==5.10.0"
virtualenv = "==20.31.2"
watchfiles = "==1.0.5"
websockets = "==15.0.1"
zipp = "==3.21.0"
zstandard = "==0.23.0"




[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[tool.poetry.scripts]
embeddingservice = "app.main:main"